### PR TITLE
add CharacterTokenizer

### PR DESCRIPTION
**Pull request by jun-harashima**
@himkt please review 🙇

### CODE REVIEW

**Comment by himkt** [comment]
@jun-harashima Thanks for the PR!
I want to use `WordTokenizer` as a general purpose tokenizer for tokenizing a sentence into (words|characters|sub-words).
So, I would like to create a character-based tokenizer the following way personally.

```python
tokenizer = WordTokenizer('Character')
tokenizer.tokenize('我輩は猫である')  # -> ['吾', '輩', 'は', '猫', 'で', 'あ', 'る']
```

What do you think about this interface?
And currently, I'm working on adding character-based/sub-word tokenizers.
If you are OK for this interface, please wait a day, please.

**Comment by himkt** [comment]
ref. https://github.com/himkt/tiny_tokenizer/blob/master/tiny_tokenizer/word_tokenizer.py#L51

**Comment by jun-harashima** [comment]
> What do you think about this interface?

**Sentence**Tokenizer splits a document into **sentences**. Similarly, **Word**Tokenizer splits a sentence into **words**. Thus, it seems to be natural that the name of a tokenizer which splits a sentence into **characters** is **Character**Tokenizer. But, its IMO.

> And currently, I'm working on adding character-based/sub-word tokenizers.
> If you are OK for this interface, please wait a day, please.

Thank you! So, I withdraw this PR 🙏

**Comment by himkt** [comment]
>  it seems to be natural that the name of a tokenizer which splits a sentence into characters is CharacterTokenizer

I totally agree with you.
In this time, I only focus on distinguishing between `Document tokenizer` and `Sentence tokenizer`.
I consider to adding `CharacterTokenizer`, thanks!

**Pull request closed without merging**
